workflows:
  my-workflow:
    scripts:
      - name: Install dependencies
        script: npm ci
      - name: Switch to a specific version of Cordova
        script: |
          set -e # exit on first failed command

          quasar mode add cordova
      - name: Add iOS platform
        script: |
          set -e # exit on first failed command

          cordova platform add
          cordova plugin add cordova-plugin-ionic-webview
          cordova plugin add cordova-plugin-wkwebview-engine
      - name: Build iOS release
        script: |
          set -e # exit on first failed command
          quasar build -m cordova -T ios
