workflows:
  my-workflow:
    scripts:
      - name: Install dependencies
        script: npm ci
      - name: Switch to a specific version of Cordova
        script: |
          set -e # exit on first failed command
          npm install -g @quasar/cli
          quasar mode add cordova
      - name: Add iOS platform
        script: |
          set -e # exit on first failed command
          cd ./src-cordova
          cordova platform add ios
          cordova plugin add cordova-plugin-ionic-webview
      - name: Build iOS release
        script: |
          set -e # exit on first failed command
          cd ../
          quasar build -m cordova -T ios
