workflows:
  my-workflow:
    scripts:
      - name: Install dependencies
        script: npm ci
      - name: Switch to a specific version of Cordova
        script: |
          set -e # exit on first failed command
          npm install -g @quasar/cli
          quasar mode add cordova
      - name: Add iOS platform
        script: |
          set -e # exit on first failed command
      - name: Build iOS release
        script: |
          set -e # exit on first failed command
          quasar build -m cordova -T ios
          ls ./dist/cordova/
    artifacts:
      - /dist/cordova/*.ipa
